include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    prefer_relative_imports: true
    non_constant_identifier_names: false
    omit_local_variable_types: false
    always_declare_return_types: true
    unnecessary_statements: true
    use_key_in_widget_constructors: true
    avoid_function_literals_in_foreach_calls: true
    avoid_js_rounded_ints: true
    camel_case_types: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false