// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM8gw6Tw1e40l25AhZoP4EsDz0YCtCcgM',
    appId: '1:81985366986:web:363983465680df542e7d33',
    messagingSenderId: '81985366986',
    projectId: 'rtc-camera-b3d5a',
    authDomain: 'rtc-camera-b3d5a.firebaseapp.com',
    storageBucket: 'rtc-camera-b3d5a.appspot.com',
    measurementId: 'G-W9XQ5CT40R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8pik8c-fvEI6hHePHwpoDLTC01eG-SA',
    appId: '1:81985366986:android:6045d28eb9c6a5382e7d33',
    messagingSenderId: '81985366986',
    projectId: 'rtc-camera-b3d5a',
    storageBucket: 'rtc-camera-b3d5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChx04UuXOmR3RR2CRxmfS8MUHAmF3dmJM',
    appId: '1:81985366986:ios:8c975bf3741a05982e7d33',
    messagingSenderId: '81985366986',
    projectId: 'rtc-camera-b3d5a',
    storageBucket: 'rtc-camera-b3d5a.appspot.com',
    iosBundleId: 'com.example.rtcCamera',
  );

}